[package]
name = "slang-rs"
version = "0.23.0"
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0"
description = "Rust bindings for the Slang Verilog parser"
repository = "https://github.com/xlsynth/slang-rs.git"
homepage = "https://github.com/xlsynth/slang-rs.git"
documentation = "https://docs.rs/slang-rs"
links = "svlang"

[dependencies]
cxx = "1.0"
indexmap = "2.14.2"
num-bigint = "0.4.3"

[build-dependencies]
cxx-build = "1.0"
cmake = "0.1"
sha2 = "0.10"

[dev-dependencies]
tempfile = "3"
serde_json = "1.0.128"
cargo_metadata = "0.18"
curl = "0.4"
log = "0.4"
toml = "0.5"
semver = "1.0"
env_logger = "0.11"
